### ISSUE TITLE
RasterData through MapServer endpoint

### ISSUE THREAD

**Issue by d-paulus** [doneill/koop-provider-pg#10]
I have raster/tiles data in an Azure PostgreSQL/PostGIS database. Querying [https://localhost:8080/pg/public.rasterdb/MapServer](https://localhost:8080/pg/public.mypgsqldb/MapServer) returns "Internal Server Error" with the following log message:

`TypeError: Cannot read properties of null (reading 'f_geometry_column')
    at C:\Users\...\pg-koop\pg-koop\node_modules\koop-provider-pg\src\model\index.js:17:27
{"level":"error","message":"error TypeError: Cannot read properties of null (reading 'f_geometry_column') on getGeometryColumn(public, rasterdb)","stack":"Error: TypeError: Cannot read properties of null (reading 'f_geometry_column') on getGeometryColumn(public, rasterdb)\n    at C:\\Users\\...\\pg-koop\\pg-koop\\node_modules\\koop-provider-pg\\src\\model\\index.js:44:16"}`

Querying [https://localhost:8080/pg/public.yem_geojson/FeatureServer/0/query](https://localhost:8080/pg/public.yem_geojson/FeatureServer/0/query) works fine with feature data in another Azure PostgreSQL/PostGIS DB.

**Comment by d-paulus** [comment]
Would appreciate any guidance on how to get the MapServer endpoint working for raster/tiles data in an Azure PostgreSQL/PostGIS DB. Thanks!

**Comment by doneill** [comment]
Excuse my delayed response, raster tiles are not supported as they do not have a geometry column like vector data.  Would have to add support for raster column.

**Comment by d-paulus** [comment]
No problem, thanks for getting back. Any plans to support raster column some time soon?

**Comment by doneill** [comment]
No, not anytime soon
