### ISSUE TITLE
multiple PG_OBJECTID column names?

### ISSUE THREAD

**Issue by rotten** [doneill/koop-provider-pg#14]
I have multiple tables in my PostGIS database but they don't all have the same unique identifier as the column name.  Is there a way to support a different identifier for each table - or do I have to change my database to ensure the column name is the same for each table?  (or put views on them)

**Comment by doneill** [comment]
Currently the provider expects a consistent unique identifier across all tables which defaults to `gid` or can be set with the `PG_OBJECTID` variable

```
# value should be String, eg. "id"
export PG_OBJECTID="${OBJECT_ID}"
```
