### ISSUE TITLE
Where to place id field configuration?

### ISSUE THREAD

**Issue by maptastik** [doneill/koop-provider-pg#7]
Reading through the documentation on how to set up koop with this provider plugin, I've run into a snag with setting a custom value for the OBJECTID. The docs say I can do the following:

```
export PG_OBJECTID=<idField>
```
What I don't understand is where in the many possible files in my koop project this should go. Can you clarify where one would set this environment variable? Thanks!

**Comment by doneill** [comment]
@maptastik Sure, the `PG_OBJECTID` can be configured/added to your  [DB Configuration](https://github.com/doneill/koop-provider-pg#database-configuration) env variables.
